style: Update to 2 spaces

diff --git a/autotag b/autotag
--- a/autotag
+++ b/autotag
@@ -23,43 +23,43 @@ Flags:
 "
 
 if [[ "$#" -eq 0 ]] || [[ "$1" == '-h' ]] || [[ "$1" == '--help' ]]; then
-    echo "$HELP"
-    exit 1
+  echo "$HELP"
+  exit 1
 fi
 LEVEL_CHOICE=$1
 
 if [[ "$2" ]]; then
-    if [[ "$2" == '-p' ]] || [[ "$2" == '--preview' ]]; then
-        PREVIEW=true
-    else
-        echo "Invalid arguments: \"$*\""
-        echo
-        echo "$USAGE"
-        exit 1
-    fi
-else
-    PREVIEW=false
-fi
-
-case $LEVEL_CHOICE in
-"M")
-    ((MAJOR += 1))
-    MINOR=0
-    BUG=0
-    ;;
-"m")
-    ((MINOR += 1))
-    BUG=0
-    ;;
-"b")
-    ((BUG += 1))
-    ;;
-*)
+  if [[ "$2" == '-p' ]] || [[ "$2" == '--preview' ]]; then
+    PREVIEW=true
+  else
     echo "Invalid arguments: \"$*\""
     echo
     echo "$USAGE"
     exit 1
-    ;;
+  fi
+else
+  PREVIEW=false
+fi
+
+case $LEVEL_CHOICE in
+"M")
+  ((MAJOR += 1))
+  MINOR=0
+  BUG=0
+  ;;
+"m")
+  ((MINOR += 1))
+  BUG=0
+  ;;
+"b")
+  ((BUG += 1))
+  ;;
+*)
+  echo "Invalid arguments: \"$*\""
+  echo
+  echo "$USAGE"
+  exit 1
+  ;;
 esac
 
 echo 'Fetching tags...'
@@ -85,8 +85,8 @@ NEW_TAG="v$MAJOR.$MINOR.$BUG"
 echo "New tag: $NEW_TAG"
 
 if [[ "$PREVIEW" == true ]]; then
-    echo 'Skipping tag creation'
+  echo 'Skipping tag creation'
 else
-    echo "Creating annotated tag..."
-    git tag -a $NEW_TAG -m $NEW_TAG
+  echo "Creating annotated tag..."
+  git tag -a $NEW_TAG -m $NEW_TAG
 fi
